weights: yolov7.pt
cfg: ''
data: yolov7/sar_ship_dataset.yaml
hyp: ./yolov7/data/hyp.scratch.p5.yaml
epochs: 1
batch_size: 5
img_size:
- 800
- 800
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: sar-ship-detection
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
world_size: 1
global_rank: -1
save_dir: sar-ship-detection/exp
total_batch_size: 5
